spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.14.40.132:8848
        namespace: 8bb51937-e343-407e-9daa-df26942d30f9
    gateway:
      discovery:
        locator:
          enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
rocketmq:
  name-server: 106.14.40.132:9876
  producer:
    group: rdp-group-dev
