spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.14.40.132:8848
        namespace: 8bb51937-e343-407e-9daa-df26942d30f9
        metadata:
          key: value
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  key: value
