spring:
  profiles:
    active: dev
  application:
    name: rdp-auth-server
server:
  port: 9090

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
info:
  key: value