spring:
  cloud:
    nacos:
      discovery:
        server-addr: rdp.uwjx.com:8848
        namespace: 8bb51937-e343-407e-9daa-df26942d30f9
ribbon:
  eager-load:
    enabled: true
    clients: rdp-auth-server
logging:
  level:
    com.rx.rdp.app: debug
feign:
  client:
    config:
      ## 全局维度配置
      default:
        loggerLevel: BASIC
      ## 服务维度配置
      rdp-auth-server:
        loggerLevel: FULL
#  httpclient:
#    enabled: true
#    max-connections: 200
#    max-connections-per-route: 50
  okhttp:
    enabled: true
